version: "3.3"
services:
  audiozpravy-api:
    container_name: audiozpravy-api
    restart: always
    build: .
    ports:
      - "8000:8000"
  audiozpravy-db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "audiozpravy" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres:/data/postgres
      - ./docker/postgres.sh:/docker-entrypoint-initdb.d/postgres.sh
    ports:
      - "${DB_PORT}:5432"
    networks:
      - postgres
    restart: always
volumes:
  postgres:
networks:
  postgres:
    driver: bridge
