version: "3.3"
services:
  audiozpravy-api:
    container_name: audiozpravy-api
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
  audiozpravy-db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: audiozpravy
      POSTGRES_PASSWORD: AZURE999audio
      POSTGRES_DB: audiozpravy
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "audiozpravy" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres:/data/postgres
      - ./docker/postgres.sh:/docker-entrypoint-initdb.d/postgres.sh
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
volumes:
  postgres:
networks:
  postgres:
    driver: bridge
