<version: "3.3"
services:
  audiozpravy-api:
    container_name: audiozpravy-api
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
volumes:
  static_volume:
