version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: techanalyzer-django-prod
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - django
volumes:
  static_volume:


#command: gunicorn API.wsgi:application --bind 0.0.0.0:8000
#command: python manage.py runserver
